### ISSUE TITLE
Minify option [feature request]

### ISSUE THREAD

**Issue by odensc** [BlitzBanana/webpack-mjml-loader#2]
It would be nice to have the ability to pass `minify: true` along to MJML.

**Comment by BlitzBanana** [comment]
Done.

You can pass all mjml options you want.
Option object provided to the loader is forwarded to `mjml()`.

**Comment by BlitzBanana** [comment]
Minify option is deprecated in the last versions of mjml, see #26.
Waiting for more infos about mjml 5 apis to update this module.
