### ISSUE TITLE
"minify" option is deprecated in mjml-core and only available in mjml cli

### ISSUE THREAD

**Issue by yvele** [BlitzBanana/webpack-mjml-loader#26]
With mjml v4.13.0 and webpack-mjml-loader v2.0.1 and

```js
module : {
  rules : [{
    test : /\.mjml$/,
    use : [{
      loader : "webpack-mjml-loader",
      options : { minify: true }
    }]
  }]
}
```

I got the following warning:

> "minify" option is deprecated in mjml-core and only available in mjml cli

Looks like `minify` is deprecated and will be removed from mjml v5 🤔 
 - https://github.com/mjmlio/mjml/issues/2277

Maybe you should update the readme sample config?

https://github.com/BlitzBanana/webpack-mjml-loader/blob/ddd6e9255494baac1a74ab3df3f5f62e3753c02d/README.md?plain=1#L27-L43

**Comment by BlitzBanana** [comment]
Thanks for the report, waiting for more infos about the breaking changes of mjml v5.
I'm updating the readme for now.
